# Generated by Django 4.2.1 on 2023-09-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_room_service_setting_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homebanner",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
